---
development:
  cloud_name: db58azw0r
  api_key: '235237333833153'
  api_secret: 5RCUhkkh8VBvmvNMeYWrz0LNzSA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: db58azw0r
  api_key: '235237333833153'
  api_secret: 5RCUhkkh8VBvmvNMeYWrz0LNzSA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: db58azw0r
  api_key: '235237333833153'
  api_secret: 5RCUhkkh8VBvmvNMeYWrz0LNzSA
  enhance_image_tag: true
  static_image_support: false
