user:
 name:
  max_length: 50
  presence: true
 email:
  max_length: 255
  presence: true
  uniqueness: { case_sensitive: false }
 password:
  min_length: 6
  presence: true
 paginate:
  per_page: 20
 gravatar:
  size: 50
 reset_password:
  expire_time_days: 2
micropost:
 content:
  max_length: 140
 per_page: 15
picture:
 max_size: 5